"""
Text Cleaner Engine for Investigative Documents & OCR Output
-------------------------------------------------------------
Preprocesses raw text from typed reports, FIRs, and OCR extractions:
- Fixes broken words split across line breaks (hyphenation repair)
- Replaces typographic ligatures and invisible unicode characters
- Normalizes whitespace, quotes, bullets, and currency symbols
- Preserves domain tokens (FIR IDs, Account IDs, License plates, Phone numbers)
"""

import re
import unicodedata
from typing import Dict, Any

# Common ligatures generated by OCR engines
LIGATURE_MAP = {
    "\ufb00": "ff",
    "\ufb01": "fi",
    "\ufb02": "fl",
    "\ufb03": "ffi",
    "\ufb04": "ffl",
    "\ufb05": "ft",
    "\ufb06": "st",
    "“": '"',
    "”": '"',
    "‘": "'",
    "’": "'",
    "`": "'",
    "–": "-",
    "—": "-",
    "…": "...",
    "\xa0": " ",       # Non-breaking space
    "\u200b": "",      # Zero-width space
    "\u200c": "",      # Zero-width non-joiner
    "\u200d": "",      # Zero-width joiner
    "\ufeff": "",      # Byte order mark
}

# Bullets & list markers normalization
BULLET_CHARS = ["•", "▪", "►", "◆", "●", "★", "–", "—"]

def clean_text(raw_text: str) -> str:
    """
    Clean and normalize raw document text before NLP parsing.
    
    Parameters
    ----------
    raw_text : str - uncleaned input text from typed input, FIRs, or OCR
    
    Returns
    -------
    str - cleaned, normalized text
    """
    if not raw_text:
        return ""

    text = raw_text

    # 1. Normalize unicode form (NFKC helps compose/decompose characters cleanly)
    text = unicodedata.normalize("NFKC", text)

    # 2. Replace known OCR ligatures and typographical punctuation
    for char, replacement in LIGATURE_MAP.items():
        text = text.replace(char, replacement)

    # 3. Standardize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # 4. Repair words split across line breaks with hyphens
    # e.g., "trans-\nfer" -> "transfer", "inves-\ntigation" -> "investigation"
    # Avoid merging license plates or valid hyphenated identifiers:
    # Look for a lowercase word part followed by -\n and lowercase word part
    def _dehyphenate(match):
        w1, w2 = match.group(1), match.group(2)
        # If it looks like a standard split English word, join directly
        return f"{w1}{w2}"

    text = re.sub(r"\b([a-zA-Z]{2,})-\s*\n\s*([a-zA-Z]{2,})\b", _dehyphenate, text)

    # 5. Normalize bullets
    for b in BULLET_CHARS:
        text = text.replace(f"\n{b} ", "\n- ")

    # 6. Standardize currency expressions (Rs. 4,50,000 / INR 450000 / ₹4,50,000)
    # Ensure uniform '₹' symbol with standard spacing
    text = re.sub(r"\b(?:Rs\.?|INR)\s*([0-9,]+(?:\.\d{2})?)\b", r"₹\1", text, flags=re.IGNORECASE)

    # 7. Collapse tabs and redundant horizontal whitespace within lines
    text = re.sub(r"[ \t]+", " ", text)

    # 8. Clean up spaces around newlines
    text = re.sub(r" *\n *", "\n", text)

    # 9. Collapse 3 or more consecutive newlines into 2
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def get_text_cleaning_stats(raw_text: str, cleaned_text: str) -> Dict[str, Any]:
    """
    Generate diagnostic statistics about text cleaning results.
    """
    return {
        "raw_length": len(raw_text or ""),
        "cleaned_length": len(cleaned_text or ""),
        "chars_removed": len(raw_text or "") - len(cleaned_text or ""),
        "lines_count": len(cleaned_text.splitlines()) if cleaned_text else 0,
    }
